name: Test
on: push
permissions:
  contents: read

jobs:
  check:
    name: Gradle check
    runs-on: ubuntu-latest
    steps:
      - name: Git clone
        uses: actions/checkout@v7
      - name: Install Java
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version-file: .java-version
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Check
        run: ./gradlew check
